/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVeiculosRouteImport } from './routes/_app.veiculos'
import { Route as AppScannerRouteImport } from './routes/_app.scanner'
import { Route as AppSaidasRouteImport } from './routes/_app.saidas'
import { Route as AppRncsRouteImport } from './routes/_app.rncs'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppRecebimentoRouteImport } from './routes/_app.recebimento'
import { Route as AppPcpRouteImport } from './routes/_app.pcp'
import { Route as AppOpConsultaRouteImport } from './routes/_app.op-consulta'
import { Route as AppMovimentacoesRouteImport } from './routes/_app.movimentacoes'
import { Route as AppInspecoesRouteImport } from './routes/_app.inspecoes'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppEstoqueRouteImport } from './routes/_app.estoque'
import { Route as AppDebugSupabaseRouteImport } from './routes/_app.debug-supabase'
import { Route as AppDebugEnvRouteImport } from './routes/_app.debug-env'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppAprovacoesRouteImport } from './routes/_app.aprovacoes'
import { Route as AppPcpIndexRouteImport } from './routes/_app.pcp.index'
import { Route as AppPalletsIndexRouteImport } from './routes/_app.pallets.index'
import { Route as AppInspecaoIndexRouteImport } from './routes/_app.inspecao.index'
import { Route as AppPcpSaldosRouteImport } from './routes/_app.pcp.saldos'
import { Route as AppPcpRoteirosRouteImport } from './routes/_app.pcp.roteiros'
import { Route as AppPcpOpsRouteImport } from './routes/_app.pcp.ops'
import { Route as AppPcpEstruturasRouteImport } from './routes/_app.pcp.estruturas'
import { Route as AppPalletsCodigoRouteImport } from './routes/_app.pallets.$codigo'
import { Route as AppInspecaoRncRouteImport } from './routes/_app.inspecao.rnc'
import { Route as AppPcpRoteirosIdRouteImport } from './routes/_app.pcp.roteiros.$id'
import { Route as AppPcpEstruturasIdRouteImport } from './routes/_app.pcp.estruturas.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosRoute = AppVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppSaidasRoute = AppSaidasRouteImport.update({
  id: '/saidas',
  path: '/saidas',
  getParentRoute: () => AppRoute,
} as any)
const AppRncsRoute = AppRncsRouteImport.update({
  id: '/rncs',
  path: '/rncs',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppRecebimentoRoute = AppRecebimentoRouteImport.update({
  id: '/recebimento',
  path: '/recebimento',
  getParentRoute: () => AppRoute,
} as any)
const AppPcpRoute = AppPcpRouteImport.update({
  id: '/pcp',
  path: '/pcp',
  getParentRoute: () => AppRoute,
} as any)
const AppOpConsultaRoute = AppOpConsultaRouteImport.update({
  id: '/op-consulta',
  path: '/op-consulta',
  getParentRoute: () => AppRoute,
} as any)
const AppMovimentacoesRoute = AppMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppInspecoesRoute = AppInspecoesRouteImport.update({
  id: '/inspecoes',
  path: '/inspecoes',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugSupabaseRoute = AppDebugSupabaseRouteImport.update({
  id: '/debug-supabase',
  path: '/debug-supabase',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugEnvRoute = AppDebugEnvRouteImport.update({
  id: '/debug-env',
  path: '/debug-env',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAprovacoesRoute = AppAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPcpIndexRoute = AppPcpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPcpRoute,
} as any)
const AppPalletsIndexRoute = AppPalletsIndexRouteImport.update({
  id: '/pallets/',
  path: '/pallets/',
  getParentRoute: () => AppRoute,
} as any)
const AppInspecaoIndexRoute = AppInspecaoIndexRouteImport.update({
  id: '/inspecao/',
  path: '/inspecao/',
  getParentRoute: () => AppRoute,
} as any)
const AppPcpSaldosRoute = AppPcpSaldosRouteImport.update({
  id: '/saldos',
  path: '/saldos',
  getParentRoute: () => AppPcpRoute,
} as any)
const AppPcpRoteirosRoute = AppPcpRoteirosRouteImport.update({
  id: '/roteiros',
  path: '/roteiros',
  getParentRoute: () => AppPcpRoute,
} as any)
const AppPcpOpsRoute = AppPcpOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AppPcpRoute,
} as any)
const AppPcpEstruturasRoute = AppPcpEstruturasRouteImport.update({
  id: '/estruturas',
  path: '/estruturas',
  getParentRoute: () => AppPcpRoute,
} as any)
const AppPalletsCodigoRoute = AppPalletsCodigoRouteImport.update({
  id: '/pallets/$codigo',
  path: '/pallets/$codigo',
  getParentRoute: () => AppRoute,
} as any)
const AppInspecaoRncRoute = AppInspecaoRncRouteImport.update({
  id: '/inspecao/rnc',
  path: '/inspecao/rnc',
  getParentRoute: () => AppRoute,
} as any)
const AppPcpRoteirosIdRoute = AppPcpRoteirosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPcpRoteirosRoute,
} as any)
const AppPcpEstruturasIdRoute = AppPcpEstruturasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPcpEstruturasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/aprovacoes': typeof AppAprovacoesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/debug-env': typeof AppDebugEnvRoute
  '/debug-supabase': typeof AppDebugSupabaseRoute
  '/estoque': typeof AppEstoqueRoute
  '/historico': typeof AppHistoricoRoute
  '/inspecoes': typeof AppInspecoesRoute
  '/movimentacoes': typeof AppMovimentacoesRoute
  '/op-consulta': typeof AppOpConsultaRoute
  '/pcp': typeof AppPcpRouteWithChildren
  '/recebimento': typeof AppRecebimentoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/rncs': typeof AppRncsRoute
  '/saidas': typeof AppSaidasRoute
  '/scanner': typeof AppScannerRoute
  '/veiculos': typeof AppVeiculosRoute
  '/inspecao/rnc': typeof AppInspecaoRncRoute
  '/pallets/$codigo': typeof AppPalletsCodigoRoute
  '/pcp/estruturas': typeof AppPcpEstruturasRouteWithChildren
  '/pcp/ops': typeof AppPcpOpsRoute
  '/pcp/roteiros': typeof AppPcpRoteirosRouteWithChildren
  '/pcp/saldos': typeof AppPcpSaldosRoute
  '/inspecao/': typeof AppInspecaoIndexRoute
  '/pallets/': typeof AppPalletsIndexRoute
  '/pcp/': typeof AppPcpIndexRoute
  '/pcp/estruturas/$id': typeof AppPcpEstruturasIdRoute
  '/pcp/roteiros/$id': typeof AppPcpRoteirosIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/aprovacoes': typeof AppAprovacoesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/debug-env': typeof AppDebugEnvRoute
  '/debug-supabase': typeof AppDebugSupabaseRoute
  '/estoque': typeof AppEstoqueRoute
  '/historico': typeof AppHistoricoRoute
  '/inspecoes': typeof AppInspecoesRoute
  '/movimentacoes': typeof AppMovimentacoesRoute
  '/op-consulta': typeof AppOpConsultaRoute
  '/recebimento': typeof AppRecebimentoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/rncs': typeof AppRncsRoute
  '/saidas': typeof AppSaidasRoute
  '/scanner': typeof AppScannerRoute
  '/veiculos': typeof AppVeiculosRoute
  '/': typeof AppIndexRoute
  '/inspecao/rnc': typeof AppInspecaoRncRoute
  '/pallets/$codigo': typeof AppPalletsCodigoRoute
  '/pcp/estruturas': typeof AppPcpEstruturasRouteWithChildren
  '/pcp/ops': typeof AppPcpOpsRoute
  '/pcp/roteiros': typeof AppPcpRoteirosRouteWithChildren
  '/pcp/saldos': typeof AppPcpSaldosRoute
  '/inspecao': typeof AppInspecaoIndexRoute
  '/pallets': typeof AppPalletsIndexRoute
  '/pcp': typeof AppPcpIndexRoute
  '/pcp/estruturas/$id': typeof AppPcpEstruturasIdRoute
  '/pcp/roteiros/$id': typeof AppPcpRoteirosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/aprovacoes': typeof AppAprovacoesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/debug-env': typeof AppDebugEnvRoute
  '/_app/debug-supabase': typeof AppDebugSupabaseRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/inspecoes': typeof AppInspecoesRoute
  '/_app/movimentacoes': typeof AppMovimentacoesRoute
  '/_app/op-consulta': typeof AppOpConsultaRoute
  '/_app/pcp': typeof AppPcpRouteWithChildren
  '/_app/recebimento': typeof AppRecebimentoRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/rncs': typeof AppRncsRoute
  '/_app/saidas': typeof AppSaidasRoute
  '/_app/scanner': typeof AppScannerRoute
  '/_app/veiculos': typeof AppVeiculosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/inspecao/rnc': typeof AppInspecaoRncRoute
  '/_app/pallets/$codigo': typeof AppPalletsCodigoRoute
  '/_app/pcp/estruturas': typeof AppPcpEstruturasRouteWithChildren
  '/_app/pcp/ops': typeof AppPcpOpsRoute
  '/_app/pcp/roteiros': typeof AppPcpRoteirosRouteWithChildren
  '/_app/pcp/saldos': typeof AppPcpSaldosRoute
  '/_app/inspecao/': typeof AppInspecaoIndexRoute
  '/_app/pallets/': typeof AppPalletsIndexRoute
  '/_app/pcp/': typeof AppPcpIndexRoute
  '/_app/pcp/estruturas/$id': typeof AppPcpEstruturasIdRoute
  '/_app/pcp/roteiros/$id': typeof AppPcpRoteirosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/aprovacoes'
    | '/configuracoes'
    | '/debug-env'
    | '/debug-supabase'
    | '/estoque'
    | '/historico'
    | '/inspecoes'
    | '/movimentacoes'
    | '/op-consulta'
    | '/pcp'
    | '/recebimento'
    | '/relatorios'
    | '/rncs'
    | '/saidas'
    | '/scanner'
    | '/veiculos'
    | '/inspecao/rnc'
    | '/pallets/$codigo'
    | '/pcp/estruturas'
    | '/pcp/ops'
    | '/pcp/roteiros'
    | '/pcp/saldos'
    | '/inspecao/'
    | '/pallets/'
    | '/pcp/'
    | '/pcp/estruturas/$id'
    | '/pcp/roteiros/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/aprovacoes'
    | '/configuracoes'
    | '/debug-env'
    | '/debug-supabase'
    | '/estoque'
    | '/historico'
    | '/inspecoes'
    | '/movimentacoes'
    | '/op-consulta'
    | '/recebimento'
    | '/relatorios'
    | '/rncs'
    | '/saidas'
    | '/scanner'
    | '/veiculos'
    | '/'
    | '/inspecao/rnc'
    | '/pallets/$codigo'
    | '/pcp/estruturas'
    | '/pcp/ops'
    | '/pcp/roteiros'
    | '/pcp/saldos'
    | '/inspecao'
    | '/pallets'
    | '/pcp'
    | '/pcp/estruturas/$id'
    | '/pcp/roteiros/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/aprovacoes'
    | '/_app/configuracoes'
    | '/_app/debug-env'
    | '/_app/debug-supabase'
    | '/_app/estoque'
    | '/_app/historico'
    | '/_app/inspecoes'
    | '/_app/movimentacoes'
    | '/_app/op-consulta'
    | '/_app/pcp'
    | '/_app/recebimento'
    | '/_app/relatorios'
    | '/_app/rncs'
    | '/_app/saidas'
    | '/_app/scanner'
    | '/_app/veiculos'
    | '/_app/'
    | '/_app/inspecao/rnc'
    | '/_app/pallets/$codigo'
    | '/_app/pcp/estruturas'
    | '/_app/pcp/ops'
    | '/_app/pcp/roteiros'
    | '/_app/pcp/saldos'
    | '/_app/inspecao/'
    | '/_app/pallets/'
    | '/_app/pcp/'
    | '/_app/pcp/estruturas/$id'
    | '/_app/pcp/roteiros/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/veiculos': {
      id: '/_app/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AppVeiculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scanner': {
      id: '/_app/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saidas': {
      id: '/_app/saidas'
      path: '/saidas'
      fullPath: '/saidas'
      preLoaderRoute: typeof AppSaidasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rncs': {
      id: '/_app/rncs'
      path: '/rncs'
      fullPath: '/rncs'
      preLoaderRoute: typeof AppRncsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recebimento': {
      id: '/_app/recebimento'
      path: '/recebimento'
      fullPath: '/recebimento'
      preLoaderRoute: typeof AppRecebimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcp': {
      id: '/_app/pcp'
      path: '/pcp'
      fullPath: '/pcp'
      preLoaderRoute: typeof AppPcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/op-consulta': {
      id: '/_app/op-consulta'
      path: '/op-consulta'
      fullPath: '/op-consulta'
      preLoaderRoute: typeof AppOpConsultaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movimentacoes': {
      id: '/_app/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AppMovimentacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspecoes': {
      id: '/_app/inspecoes'
      path: '/inspecoes'
      fullPath: '/inspecoes'
      preLoaderRoute: typeof AppInspecoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debug-supabase': {
      id: '/_app/debug-supabase'
      path: '/debug-supabase'
      fullPath: '/debug-supabase'
      preLoaderRoute: typeof AppDebugSupabaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debug-env': {
      id: '/_app/debug-env'
      path: '/debug-env'
      fullPath: '/debug-env'
      preLoaderRoute: typeof AppDebugEnvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aprovacoes': {
      id: '/_app/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AppAprovacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcp/': {
      id: '/_app/pcp/'
      path: '/'
      fullPath: '/pcp/'
      preLoaderRoute: typeof AppPcpIndexRouteImport
      parentRoute: typeof AppPcpRoute
    }
    '/_app/pallets/': {
      id: '/_app/pallets/'
      path: '/pallets'
      fullPath: '/pallets/'
      preLoaderRoute: typeof AppPalletsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspecao/': {
      id: '/_app/inspecao/'
      path: '/inspecao'
      fullPath: '/inspecao/'
      preLoaderRoute: typeof AppInspecaoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcp/saldos': {
      id: '/_app/pcp/saldos'
      path: '/saldos'
      fullPath: '/pcp/saldos'
      preLoaderRoute: typeof AppPcpSaldosRouteImport
      parentRoute: typeof AppPcpRoute
    }
    '/_app/pcp/roteiros': {
      id: '/_app/pcp/roteiros'
      path: '/roteiros'
      fullPath: '/pcp/roteiros'
      preLoaderRoute: typeof AppPcpRoteirosRouteImport
      parentRoute: typeof AppPcpRoute
    }
    '/_app/pcp/ops': {
      id: '/_app/pcp/ops'
      path: '/ops'
      fullPath: '/pcp/ops'
      preLoaderRoute: typeof AppPcpOpsRouteImport
      parentRoute: typeof AppPcpRoute
    }
    '/_app/pcp/estruturas': {
      id: '/_app/pcp/estruturas'
      path: '/estruturas'
      fullPath: '/pcp/estruturas'
      preLoaderRoute: typeof AppPcpEstruturasRouteImport
      parentRoute: typeof AppPcpRoute
    }
    '/_app/pallets/$codigo': {
      id: '/_app/pallets/$codigo'
      path: '/pallets/$codigo'
      fullPath: '/pallets/$codigo'
      preLoaderRoute: typeof AppPalletsCodigoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspecao/rnc': {
      id: '/_app/inspecao/rnc'
      path: '/inspecao/rnc'
      fullPath: '/inspecao/rnc'
      preLoaderRoute: typeof AppInspecaoRncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcp/roteiros/$id': {
      id: '/_app/pcp/roteiros/$id'
      path: '/$id'
      fullPath: '/pcp/roteiros/$id'
      preLoaderRoute: typeof AppPcpRoteirosIdRouteImport
      parentRoute: typeof AppPcpRoteirosRoute
    }
    '/_app/pcp/estruturas/$id': {
      id: '/_app/pcp/estruturas/$id'
      path: '/$id'
      fullPath: '/pcp/estruturas/$id'
      preLoaderRoute: typeof AppPcpEstruturasIdRouteImport
      parentRoute: typeof AppPcpEstruturasRoute
    }
  }
}

interface AppPcpEstruturasRouteChildren {
  AppPcpEstruturasIdRoute: typeof AppPcpEstruturasIdRoute
}

const AppPcpEstruturasRouteChildren: AppPcpEstruturasRouteChildren = {
  AppPcpEstruturasIdRoute: AppPcpEstruturasIdRoute,
}

const AppPcpEstruturasRouteWithChildren =
  AppPcpEstruturasRoute._addFileChildren(AppPcpEstruturasRouteChildren)

interface AppPcpRoteirosRouteChildren {
  AppPcpRoteirosIdRoute: typeof AppPcpRoteirosIdRoute
}

const AppPcpRoteirosRouteChildren: AppPcpRoteirosRouteChildren = {
  AppPcpRoteirosIdRoute: AppPcpRoteirosIdRoute,
}

const AppPcpRoteirosRouteWithChildren = AppPcpRoteirosRoute._addFileChildren(
  AppPcpRoteirosRouteChildren,
)

interface AppPcpRouteChildren {
  AppPcpEstruturasRoute: typeof AppPcpEstruturasRouteWithChildren
  AppPcpOpsRoute: typeof AppPcpOpsRoute
  AppPcpRoteirosRoute: typeof AppPcpRoteirosRouteWithChildren
  AppPcpSaldosRoute: typeof AppPcpSaldosRoute
  AppPcpIndexRoute: typeof AppPcpIndexRoute
}

const AppPcpRouteChildren: AppPcpRouteChildren = {
  AppPcpEstruturasRoute: AppPcpEstruturasRouteWithChildren,
  AppPcpOpsRoute: AppPcpOpsRoute,
  AppPcpRoteirosRoute: AppPcpRoteirosRouteWithChildren,
  AppPcpSaldosRoute: AppPcpSaldosRoute,
  AppPcpIndexRoute: AppPcpIndexRoute,
}

const AppPcpRouteWithChildren =
  AppPcpRoute._addFileChildren(AppPcpRouteChildren)

interface AppRouteChildren {
  AppAprovacoesRoute: typeof AppAprovacoesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDebugEnvRoute: typeof AppDebugEnvRoute
  AppDebugSupabaseRoute: typeof AppDebugSupabaseRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppInspecoesRoute: typeof AppInspecoesRoute
  AppMovimentacoesRoute: typeof AppMovimentacoesRoute
  AppOpConsultaRoute: typeof AppOpConsultaRoute
  AppPcpRoute: typeof AppPcpRouteWithChildren
  AppRecebimentoRoute: typeof AppRecebimentoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppRncsRoute: typeof AppRncsRoute
  AppSaidasRoute: typeof AppSaidasRoute
  AppScannerRoute: typeof AppScannerRoute
  AppVeiculosRoute: typeof AppVeiculosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInspecaoRncRoute: typeof AppInspecaoRncRoute
  AppPalletsCodigoRoute: typeof AppPalletsCodigoRoute
  AppInspecaoIndexRoute: typeof AppInspecaoIndexRoute
  AppPalletsIndexRoute: typeof AppPalletsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAprovacoesRoute: AppAprovacoesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDebugEnvRoute: AppDebugEnvRoute,
  AppDebugSupabaseRoute: AppDebugSupabaseRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppInspecoesRoute: AppInspecoesRoute,
  AppMovimentacoesRoute: AppMovimentacoesRoute,
  AppOpConsultaRoute: AppOpConsultaRoute,
  AppPcpRoute: AppPcpRouteWithChildren,
  AppRecebimentoRoute: AppRecebimentoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppRncsRoute: AppRncsRoute,
  AppSaidasRoute: AppSaidasRoute,
  AppScannerRoute: AppScannerRoute,
  AppVeiculosRoute: AppVeiculosRoute,
  AppIndexRoute: AppIndexRoute,
  AppInspecaoRncRoute: AppInspecaoRncRoute,
  AppPalletsCodigoRoute: AppPalletsCodigoRoute,
  AppInspecaoIndexRoute: AppInspecaoIndexRoute,
  AppPalletsIndexRoute: AppPalletsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
